package core;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.document.Item;

/**
 * Created by remy on 09/10/15.
 */
public class DVD extends Item {
    private int productID;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "productID")
    public int getDVDId(){
        return productID;
    }
}
